# Generated by Django 3.2 on 2021-08-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_productcategory_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
