# Generated by Django 3.2 on 2021-07-23 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210721_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expiring',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 20, 25, 51, 484697, tzinfo=utc)),
        ),
    ]
